In [1]:
import numpy as np
from sklearn.decomposition import NMF
import pandas as pd
import random

In [2]:
ratings = pd.read_csv('ratings.csv')

In [3]:
ratings

userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [4]:
movies = pd.read_csv('movies.csv')

In [5]:
moviesIdlist=movies['movieId'].tolist()

In [6]:
MOVIES = [x[:-7] for x in (pd.read_csv('movies.csv'))['title'].values.tolist()]

In [7]:
MOVIES

['Toy Story',
 'Jumanji',
 'Grumpier Old Men',
 'Waiting to Exhale',
 'Father of the Bride Part II',
 'Heat',
 'Sabrina',
 'Tom and Huck',
 'Sudden Death',
 'GoldenEye',
 'American President, The',
 'Dracula: Dead and Loving It',
 'Balto',
 'Nixon',
 'Cutthroat Island',
 'Casino',
 'Sense and Sensibility',
 'Four Rooms',
 'Ace Ventura: When Nature Calls',
 'Money Train',
 'Get Shorty',
 'Copycat',
 'Assassins',
 'Powder',
 'Leaving Las Vegas',
 'Othello',
 'Now and Then',
 'Persuasion',
 'City of Lost Children, The (Cité des enfants perdus, La)',
 'Shanghai Triad (Yao a yao yao dao waipo qiao)',
 'Dangerous Minds',
 'Twelve Monkeys (a.k.a. 12 Monkeys)',
 'Babe',
 'Dead Man Walking',
 'It Takes Two',
 'Clueless',
 'Cry, the Beloved Country',
 'Richard III',
 'Dead Presidents',
 'Restoration',
 'Mortal Kombat',
 'To Die For',
 'How to Make an American Quilt',
 'Seven (a.k.a. Se7en)',
 'Pocahontas',
 'When Night Is Falling',
 'Usual Suspects, The',
 'Mighty Aphrodite',
 'Lamerica',
 'Big 

In [8]:
MOVIEID = [x for x in (pd.read_csv('movies.csv'))['movieId'].values.tolist()]

In [9]:
len(MOVIES)

9742

In [10]:
len(MOVIEID)

9742

In [11]:
#MOVIES = list(dict.fromkeys(MOVIES))
#len(MOVIES)

In [12]:
movies['title'] = MOVIES

In [13]:
movies

movieId                               title  \
0           1                           Toy Story   
1           2                             Jumanji   
2           3                    Grumpier Old Men   
3           4                   Waiting to Exhale   
4           5         Father of the Bride Part II   
...       ...                                 ...   
9737   193581  Black Butler: Book of the Atlantic   
9738   193583               No Game No Life: Zero   
9739   193585                               Flint   
9740   193587        Bungo Stray Dogs: Dead Apple   
9741   193609        Andrew Dice Clay: Dice Rules   

                                           genres  
0     Adventure|Animation|Children|Comedy|Fantasy  
1                      Adventure|Children|Fantasy  
2                                  Comedy|Romance  
3                            Comedy|Drama|Romance  
4                                          Comedy  
...                                           ...  
9737              Action|Animation|Comedy|Fantasy  
9738                     Animation|Comedy|Fantasy  
9739                                        Drama  
9740                             Action|Animation  
9741                                       Comedy  

[9742 rows x 3 columns]

In [14]:
len(movies)

9742

In [15]:
ratings2=ratings.set_index(['userId'])

In [16]:
ratings3 = ratings.drop(['timestamp'], axis=1)

In [17]:
ratings3

userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100831     610   166534     4.0
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0

[100836 rows x 3 columns]

In [18]:
len(ratings3)

100836

In [19]:
newmoviesratings = pd.merge(ratings3, movies, on='movieId')

In [20]:
newmoviesratings

userId  movieId  rating                      title  \
0            1        1     4.0                  Toy Story   
1            5        1     4.0                  Toy Story   
2            7        1     4.5                  Toy Story   
3           15        1     2.5                  Toy Story   
4           17        1     4.5                  Toy Story   
...        ...      ...     ...                        ...   
100831     610   160341     2.5                  Bloodmoon   
100832     610   160527     4.5  Sympathy for the Underdog   
100833     610   160836     3.0                     Hazard   
100834     610   163937     3.5                Blair Witch   
100835     610   163981     3.5                         31   

                                             genres  
0       Adventure|Animation|Children|Comedy|Fantasy  
1       Adventure|Animation|Children|Comedy|Fantasy  
2       Adventure|Animation|Children|Comedy|Fantasy  
3       Adventure|Animation|Children|Comedy|Fantasy  
4       Adventure|Animation|Children|Comedy|Fantasy  
...                                             ...  
100831                              Action|Thriller  
100832                           Action|Crime|Drama  
100833                        Action|Drama|Thriller  
100834                              Horror|Thriller  
100835                                       Horror  

[100836 rows x 5 columns]

In [21]:
newmoviesratings2=newmoviesratings[['userId','title','rating']]

In [22]:
newmoviesratings2

userId                      title  rating
0            1                  Toy Story     4.0
1            5                  Toy Story     4.0
2            7                  Toy Story     4.5
3           15                  Toy Story     2.5
4           17                  Toy Story     4.5
...        ...                        ...     ...
100831     610                  Bloodmoon     2.5
100832     610  Sympathy for the Underdog     4.5
100833     610                     Hazard     3.0
100834     610                Blair Witch     3.5
100835     610                         31     3.5

[100836 rows x 3 columns]

In [23]:
newf=newmoviesratings2.set_index('userId')

In [24]:
newf

title  rating
userId                                   
1                       Toy Story     4.0
5                       Toy Story     4.0
7                       Toy Story     4.5
15                      Toy Story     2.5
17                      Toy Story     4.5
...                           ...     ...
610                     Bloodmoon     2.5
610     Sympathy for the Underdog     4.5
610                        Hazard     3.0
610                   Blair Witch     3.5
610                            31     3.5

[100836 rows x 2 columns]

In [25]:
#newf = newmoviesratings2.pivot(index='userId', columns='title')

In [26]:
ratings3 = ratings.drop(['timestamp'], axis=1)

In [27]:
newf = ratings3.pivot(index='userId', columns='movieId')

In [28]:
newf

rating                                                                 \
movieId 1      2      3      4      5      6      7      8      9      10       
userId                                                                          
1          4.0    NaN    4.0    NaN    NaN    4.0    NaN    NaN    NaN    NaN   
2          NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
3          NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
4          NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
5          4.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
...        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
606        2.5    NaN    NaN    NaN    NaN    NaN    2.5    NaN    NaN    NaN   
607        4.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
608        2.5    2.0    2.0    NaN    NaN    NaN    NaN    NaN    NaN    4.0   
609        3.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    4.0   
610        5.0    NaN    NaN    NaN    NaN    5.0    NaN    NaN    NaN    NaN   

         ...                                                                 \
movieId  ... 193565 193567 193571 193573 193579 193581 193583 193585 193587   
userId   ...                                                                  
1        ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
2        ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
3        ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
4        ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
5        ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
606      ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
607      ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
608      ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
609      ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
610      ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   

                
movieId 193609  
userId          
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
...        ...  
606        NaN  
607        NaN  
608        NaN  
609        NaN  
610        NaN  

[610 rows x 9724 columns]

In [29]:
actualmovieIdslist=ratings3['movieId'].tolist()

In [30]:
#ratingsmovieIdlist=ratings['movieId'].tolist()

In [31]:
newmoviesIDlist = [x for x in moviesIdlist if x in actualmovieIdslist]

In [32]:
len(newmoviesIDlist)

9724

In [33]:
newf2=newf.fillna(3.000000)

In [34]:
newf2

rating                                                                 \
movieId 1      2      3      4      5      6      7      8      9      10       
userId                                                                          
1          4.0    3.0    4.0    3.0    3.0    4.0    3.0    3.0    3.0    3.0   
2          3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
3          3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
4          3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
5          4.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
...        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
606        2.5    3.0    3.0    3.0    3.0    3.0    2.5    3.0    3.0    3.0   
607        4.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
608        2.5    2.0    2.0    3.0    3.0    3.0    3.0    3.0    3.0    4.0   
609        3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    4.0   
610        5.0    3.0    3.0    3.0    3.0    5.0    3.0    3.0    3.0    3.0   

         ...                                                                 \
movieId  ... 193565 193567 193571 193573 193579 193581 193583 193585 193587   
userId   ...                                                                  
1        ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
2        ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
3        ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
4        ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
5        ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
606      ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
607      ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
608      ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
609      ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
610      ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   

                
movieId 193609  
userId          
1          3.0  
2          3.0  
3          3.0  
4          3.0  
5          3.0  
...        ...  
606        3.0  
607        3.0  
608        3.0  
609        3.0  
610        3.0  

[610 rows x 9724 columns]

In [35]:
R=newf2.values

In [36]:
R

array([[4. , 3. , 4. , ..., 3. , 3. , 3. ],
       [3. , 3. , 3. , ..., 3. , 3. , 3. ],
       [3. , 3. , 3. , ..., 3. , 3. , 3. ],
       ...,
       [2.5, 2. , 2. , ..., 3. , 3. , 3. ],
       [3. , 3. , 3. , ..., 3. , 3. , 3. ],
       [5. , 3. , 3. , ..., 3. , 3. , 3. ]])

In [37]:
model = NMF(n_components=10, init='random', random_state=10)

In [38]:
model.fit(R)

NMF(alpha=0.0, beta_loss='frobenius', init='random', l1_ratio=0.0, max_iter=200,
    n_components=10, random_state=10, shuffle=False, solver='cd', tol=0.0001,
    verbose=0)

In [39]:
Q = model.components_  # movie-genre matrix

In [40]:
P = model.transform(R)  # user-genre matrix

In [41]:
print(model.reconstruction_err_)

331.7643512500957


In [42]:
nR = np.dot(P, Q)

In [43]:
nR

array([[3.85334815, 3.23929205, 3.13316885, ..., 3.00139387, 3.00351925,
        2.9891991 ],
       [3.1300499 , 3.01321034, 2.99438994, ..., 3.00257888, 3.00342496,
        3.00439365],
       [3.0503099 , 3.0147466 , 2.95610635, ..., 3.00132832, 2.99424463,
        2.98655487],
       ...,
       [3.34534593, 3.1380288 , 2.78720652, ..., 2.9785765 , 2.97658175,
        2.99924344],
       [3.18420646, 3.04170505, 3.00418841, ..., 3.00140675, 3.00088641,
        3.00066233],
       [3.70978537, 3.19320007, 2.61052062, ..., 3.03581357, 3.00096229,
        3.07564937]])

In [44]:
len(MOVIES)

9742

In [45]:
randomuser = ['Aladdin', 'Lion King, The', 'Hercules']

In [46]:
randomratings = [5,5,5]

In [47]:
len(MOVIES)

9742

In [48]:
randomlist = [3]*len(newmoviesIDlist)

In [49]:
randomlist

[3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,


In [50]:
index0=MOVIES.index(randomuser[0])

In [51]:
ID0=MOVIEID[index0]

In [52]:
index0b=newmoviesIDlist.index(ID0)

In [53]:
index0b

506

In [54]:
randomlist[index0b]=randomratings[0]

In [55]:
index1=MOVIES.index(randomuser[1])
ID1=MOVIEID[index1]
index1b=newmoviesIDlist.index(ID1)
randomlist[index1b]=randomratings[1]

In [56]:
index2=MOVIES.index(randomuser[2])
ID2=MOVIEID[index2]
index2b=newmoviesIDlist.index(ID2)
randomlist[index2b]=randomratings[2]

In [57]:
len(randomlist)

9724

In [58]:
nR

array([[3.85334815, 3.23929205, 3.13316885, ..., 3.00139387, 3.00351925,
        2.9891991 ],
       [3.1300499 , 3.01321034, 2.99438994, ..., 3.00257888, 3.00342496,
        3.00439365],
       [3.0503099 , 3.0147466 , 2.95610635, ..., 3.00132832, 2.99424463,
        2.98655487],
       ...,
       [3.34534593, 3.1380288 , 2.78720652, ..., 2.9785765 , 2.97658175,
        2.99924344],
       [3.18420646, 3.04170505, 3.00418841, ..., 3.00140675, 3.00088641,
        3.00066233],
       [3.70978537, 3.19320007, 2.61052062, ..., 3.03581357, 3.00096229,
        3.07564937]])

In [59]:
ratings3

userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100831     610   166534     4.0
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0

[100836 rows x 3 columns]

In [60]:
ratings4 = ratings3.groupby('userId')

In [61]:
maxValue = ratings3['userId'].max()

In [62]:
maxValue

610

In [63]:
newUserID=maxValue+1

In [64]:
newUserID

611

In [65]:
array3=np.array(randomlist)

In [66]:
array3

array([3, 3, 3, ..., 3, 3, 3])

In [67]:
array3=array3.reshape(1,-1)

In [68]:
#model.fit(R)

In [69]:
P = model.transform(array3)

In [70]:
P

array([[1.65003946, 0.87183689, 0.5963215 , 0.54059965, 0.51781286,
        0.34868332, 0.53000465, 0.56719135, 0.53753869, 0.37967333]])

In [71]:
nR = np.dot(P, Q)

In [72]:
finaluser=nR[-1]

In [73]:
finaluser

array([3.19489782, 3.07042325, 3.01110418, ..., 3.00305848, 2.99999424,
       2.998227  ])

In [74]:
#len(finaluser)

In [75]:
#newuserrow=[newUserID]+randomlist

In [76]:
#newuserrow

In [77]:
#newf3=newuserrow.append(newf2)

In [78]:
#newf3

In [79]:
R

In [80]:
R2=R.tolist()

In [81]:
R2[0]

In [82]:
R3 = R2 + [randomlist]

In [83]:
R3

In [84]:
R3[-1]

In [85]:
R4=np.array(R3)

In [86]:
R4

In [87]:
model.fit(R4)

In [88]:
Q = model.components_

In [89]:
P = model.transform(R4)

In [90]:
nR = np.dot(P, Q)

In [91]:
nR

array([[3.19489782, 3.07042325, 3.01110418, ..., 3.00305848, 2.99999424,
        2.998227  ]])

In [92]:
finalList=nR.tolist()

In [93]:
totalratingsnewuser=finalList[-1]

In [94]:
len(totalratingsnewuser)

9724

In [95]:
len(newmoviesIDlist)

9724

In [96]:
#index1=MOVIES.index(randomuser[1])
#ID1=MOVIEID[index1]
#index1b=newmoviesIDlist.index(ID1)
#randomlist[index1b]=randomratings[1]

In [97]:
finalDf1 = pd.DataFrame(
    {'movieid': newmoviesIDlist,
     'ratingsnewuser': totalratingsnewuser
    })

In [98]:
finalDf1

movieid  ratingsnewuser
0           1        3.194898
1           2        3.070423
2           3        3.011104
3           4        2.992578
4           5        3.028354
...       ...             ...
9719   193581        3.000223
9720   193583        3.001312
9721   193585        3.003058
9722   193587        2.999994
9723   193609        2.998227

[9724 rows x 2 columns]

In [99]:
finalDf2 = pd.DataFrame(
    {'title': MOVIES,
     'movieid': MOVIEID,
    })

In [100]:
finalDf2

title  movieid
0                              Toy Story        1
1                                Jumanji        2
2                       Grumpier Old Men        3
3                      Waiting to Exhale        4
4            Father of the Bride Part II        5
...                                  ...      ...
9737  Black Butler: Book of the Atlantic   193581
9738               No Game No Life: Zero   193583
9739                               Flint   193585
9740        Bungo Stray Dogs: Dead Apple   193587
9741        Andrew Dice Clay: Dice Rules   193609

[9742 rows x 2 columns]

In [101]:
finalDf3=finalDf2.drop_duplicates()

In [102]:
finalDf3

title  movieid
0                              Toy Story        1
1                                Jumanji        2
2                       Grumpier Old Men        3
3                      Waiting to Exhale        4
4            Father of the Bride Part II        5
...                                  ...      ...
9737  Black Butler: Book of the Atlantic   193581
9738               No Game No Life: Zero   193583
9739                               Flint   193585
9740        Bungo Stray Dogs: Dead Apple   193587
9741        Andrew Dice Clay: Dice Rules   193609

[9742 rows x 2 columns]

In [103]:
finaldf4 = pd.merge(finalDf3, finalDf1, on='movieid')

In [104]:
finaldf5=finaldf4.dropna()

In [105]:
finaldf5

title  movieid  ratingsnewuser
0                              Toy Story        1        3.194898
1                                Jumanji        2        3.070423
2                       Grumpier Old Men        3        3.011104
3                      Waiting to Exhale        4        2.992578
4            Father of the Bride Part II        5        3.028354
...                                  ...      ...             ...
9719  Black Butler: Book of the Atlantic   193581        3.000223
9720               No Game No Life: Zero   193583        3.001312
9721                               Flint   193585        3.003058
9722        Bungo Stray Dogs: Dead Apple   193587        2.999994
9723        Andrew Dice Clay: Dice Rules   193609        2.998227

[9724 rows x 3 columns]

In [106]:
finaldf6=finaldf5.sort_values('ratingsnewuser', ascending=False)

In [107]:
finalmovielist=finaldf6['title'].tolist()

In [108]:
finalmovielist

['Shawshank Redemption, The',
 'Forrest Gump',
 'Pulp Fiction',
 'Silence of the Lambs, The',
 'Braveheart',
 'Apollo 13',
 'Star Wars: Episode IV - A New Hope',
 "Schindler's List",
 'Fugitive, The',
 'Matrix, The',
 'Terminator 2: Judgment Day',
 'Jurassic Park',
 'Toy Story',
 'Lion King, The',
 'Aladdin',
 'Beauty and the Beast',
 'Dances with Wolves',
 'Independence Day (a.k.a. ID4)',
 'Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark)',
 'Usual Suspects, The',
 'Speed',
 'Star Wars: Episode V - The Empire Strikes Back',
 'Twelve Monkeys (a.k.a. 12 Monkeys)',
 'Mission: Impossible',
 'Fargo',
 'Crimson Tide',
 'Clear and Present Danger',
 'Star Wars: Episode VI - Return of the Jedi',
 'Twister',
 'True Lies',
 'Saving Private Ryan',
 "Mr. Holland's Opus",
 'Star Trek: First Contact',
 'Shrek',
 'Rock, The',
 'Seven (a.k.a. Se7en)',
 'Die Hard: With a Vengeance',
 'Firm, The',
 'Ghost',
 'Fight Club',
 'Lord of the Rings: The Fellowship of the Ring, The',
 'Am

In [109]:
finaloutputlist=finalmovielist[:8]

In [110]:
finaloutputlist

['Shawshank Redemption, The',
 'Forrest Gump',
 'Pulp Fiction',
 'Silence of the Lambs, The',
 'Braveheart',
 'Apollo 13',
 'Star Wars: Episode IV - A New Hope',
 "Schindler's List"]