In [1]:
import numpy as np
from sklearn.decomposition import NMF
import pandas as pd

In [2]:
# movie, ratings by users
data = [
    [5, 4, 1, 1, 3],
    [3, 2, 1, 3, 1],
    [3, 3, 3, 3, 5],
    [1, 1, 5, 4, 4],
]

In [3]:
columns = ['Titanic', 'Tiffany', 'Terminator', 'Star Trek', 'Star Wars'] #movies
index = ['Ada', 'Bob', 'Steve', 'Margaret'] #users

In [4]:
#need a dataframe for this
R = pd.DataFrame(data, index=index, columns=columns)

In [5]:
R

Titanic  Tiffany  Terminator  Star Trek  Star Wars
Ada             5        4           1          1          3
Bob             3        2           1          3          1
Steve           3        3           3          3          5
Margaret        1        1           5          4          4

In [6]:
R=R.values

In [7]:
R

array([[5, 4, 1, 1, 3],
       [3, 2, 1, 3, 1],
       [3, 3, 3, 3, 5],
       [1, 1, 5, 4, 4]], dtype=int64)

In [8]:
#create a model and set the hyperparameters
# model assumes R ~ PQ'
model = NMF(n_components=2, init='random', random_state=10)

In [9]:
model.fit(R)

NMF(alpha=0.0, beta_loss='frobenius', init='random', l1_ratio=0.0, max_iter=200,
    n_components=2, random_state=10, shuffle=False, solver='cd', tol=0.0001,
    verbose=0)

In [10]:
Q = model.components_  # movie-genre matrix

In [11]:
P = model.transform(R)  # user-genre matrix

In [12]:
print(model.reconstruction_err_) #reconstruction error

2.3198220110250003


In [13]:
nR = np.dot(P, Q)
print(nR) ## The reconstructed matrix!

[[4.98574011 3.98089613 0.69817861 1.52507923 2.84430572]
 [2.61580597 2.15486368 1.23495386 1.51110529 2.19736573]
 [3.35829506 2.89944467 3.32824145 3.36641177 4.23566511]
 [0.85105386 1.03300314 4.75334969 4.0532461  4.24705685]]


In [14]:
# predict the hidden features for a new data point
query = [[1, 2, 5, 4, 5]]

In [15]:
#in this case, a new user providing ratings for the 5 movies.
print(model.transform(query))

[[2.68231475 0.45631224]]


In [16]:
ratings = pd.read_csv('ratings.csv')

In [17]:
ratings

userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [18]:
ratings2=ratings.set_index(['userId'])

In [19]:
ratings2

movieId  rating   timestamp
userId                             
1             1     4.0   964982703
1             3     4.0   964981247
1             6     4.0   964982224
1            47     5.0   964983815
1            50     5.0   964982931
...         ...     ...         ...
610      166534     4.0  1493848402
610      168248     5.0  1493850091
610      168250     5.0  1494273047
610      168252     5.0  1493846352
610      170875     3.0  1493846415

[100836 rows x 3 columns]

In [20]:
ratings3 = ratings.drop(['timestamp'], axis=1)

In [21]:
ratings3

userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100831     610   166534     4.0
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0

[100836 rows x 3 columns]

In [22]:
newf = ratings3.pivot(index='userId', columns='movieId')

In [23]:
newf

rating                                                                 \
movieId 1      2      3      4      5      6      7      8      9      10       
userId                                                                          
1          4.0    NaN    4.0    NaN    NaN    4.0    NaN    NaN    NaN    NaN   
2          NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
3          NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
4          NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
5          4.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
...        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
606        2.5    NaN    NaN    NaN    NaN    NaN    2.5    NaN    NaN    NaN   
607        4.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
608        2.5    2.0    2.0    NaN    NaN    NaN    NaN    NaN    NaN    4.0   
609        3.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    4.0   
610        5.0    NaN    NaN    NaN    NaN    5.0    NaN    NaN    NaN    NaN   

         ...                                                                 \
movieId  ... 193565 193567 193571 193573 193579 193581 193583 193585 193587   
userId   ...                                                                  
1        ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
2        ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
3        ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
4        ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
5        ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
606      ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
607      ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
608      ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
609      ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
610      ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   

                
movieId 193609  
userId          
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
...        ...  
606        NaN  
607        NaN  
608        NaN  
609        NaN  
610        NaN  

[610 rows x 9724 columns]

In [24]:
newf.head(50)

rating                                                                 \
movieId 1      2      3      4      5      6      7      8      9      10       
userId                                                                          
1          4.0    NaN    4.0    NaN    NaN    4.0    NaN    NaN    NaN    NaN   
2          NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
3          NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
4          NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
5          4.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
6          NaN    4.0    5.0    3.0    5.0    4.0    4.0    3.0    NaN    3.0   
7          4.5    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
8          NaN    4.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    2.0   
9          NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
10         NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
11         NaN    NaN    NaN    NaN    NaN    5.0    NaN    NaN    NaN    3.0   
12         NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
13         NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
14         NaN    NaN    NaN    3.0    NaN    NaN    3.0    NaN    NaN    NaN   
15         2.5    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
16         NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
17         4.5    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
18         3.5    3.0    NaN    NaN    NaN    4.0    NaN    NaN    NaN    NaN   
19         4.0    3.0    3.0    NaN    NaN    NaN    2.0    NaN    NaN    2.0   
20         NaN    3.0    NaN    NaN    NaN    NaN    NaN    1.0    NaN    NaN   
21         3.5    3.5    NaN    NaN    NaN    NaN    NaN    NaN    NaN    5.0   
22         NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
23         NaN    NaN    NaN    NaN    NaN    4.0    NaN    NaN    NaN    NaN   
24         NaN    NaN    NaN    NaN    NaN    4.5    NaN    NaN    NaN    NaN   
25         NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
26         NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    3.0   
27         3.0    4.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
28         NaN    NaN    NaN    NaN    NaN    3.5    NaN    NaN    NaN    NaN   
29         NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
30         NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
31         5.0    NaN    NaN    NaN    3.0    NaN    4.0    NaN    NaN    4.0   
32         3.0    NaN    3.0    NaN    NaN    3.0    4.0    NaN    NaN    NaN   
33         3.0    NaN    NaN    NaN    NaN    NaN    1.0    NaN    NaN    NaN   
34         NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    5.0   
35         NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
36         NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
37         NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
38         NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
39         NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
40         5.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
41         NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
42         NaN    NaN    4.0    NaN    NaN    NaN    3.0    NaN    NaN    5.0   
43         5.0    NaN    5.0    NaN    5.0    NaN    5.0    5.0    NaN    4.0   
44         3.0    NaN    3.0    NaN    NaN    3.0    NaN    NaN    NaN    NaN   
45         4.0    NaN    NaN    NaN    3.0    4.0    3.0    NaN    NaN    NaN   
46         5.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    3.0   
47         NaN    NaN    NaN    NaN    

In [25]:
newf2=newf.fillna(3.000000)

In [26]:
newf2

rating                                                                 \
movieId 1      2      3      4      5      6      7      8      9      10       
userId                                                                          
1          4.0    3.0    4.0    3.0    3.0    4.0    3.0    3.0    3.0    3.0   
2          3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
3          3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
4          3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
5          4.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
...        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
606        2.5    3.0    3.0    3.0    3.0    3.0    2.5    3.0    3.0    3.0   
607        4.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
608        2.5    2.0    2.0    3.0    3.0    3.0    3.0    3.0    3.0    4.0   
609        3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    4.0   
610        5.0    3.0    3.0    3.0    3.0    5.0    3.0    3.0    3.0    3.0   

         ...                                                                 \
movieId  ... 193565 193567 193571 193573 193579 193581 193583 193585 193587   
userId   ...                                                                  
1        ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
2        ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
3        ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
4        ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
5        ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
606      ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
607      ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
608      ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
609      ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   
610      ...    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0    3.0   

                
movieId 193609  
userId          
1          3.0  
2          3.0  
3          3.0  
4          3.0  
5          3.0  
...        ...  
606        3.0  
607        3.0  
608        3.0  
609        3.0  
610        3.0  

[610 rows x 9724 columns]

In [27]:
R=newf2.values

In [28]:
R

array([[4. , 3. , 4. , ..., 3. , 3. , 3. ],
       [3. , 3. , 3. , ..., 3. , 3. , 3. ],
       [3. , 3. , 3. , ..., 3. , 3. , 3. ],
       ...,
       [2.5, 2. , 2. , ..., 3. , 3. , 3. ],
       [3. , 3. , 3. , ..., 3. , 3. , 3. ],
       [5. , 3. , 3. , ..., 3. , 3. , 3. ]])

In [29]:
model = NMF(n_components=2, init='random', random_state=10)

In [30]:
model.fit(R)

NMF(alpha=0.0, beta_loss='frobenius', init='random', l1_ratio=0.0, max_iter=200,
    n_components=2, random_state=10, shuffle=False, solver='cd', tol=0.0001,
    verbose=0)

In [31]:
Q = model.components_  # movie-genre matrix

In [32]:
P = model.transform(R)  # user-genre matrix

In [33]:
print(model.reconstruction_err_) #reconstruction error

355.71228254217317


In [34]:
nR = np.dot(P, Q)
print(nR) ## The reconstructed matrix!

[[3.35258076 3.10229298 3.04739491 ... 3.02653979 3.02618695 3.02742886]
 [3.31846793 3.07282644 3.0163407  ... 2.99443471 2.99456551 2.99523288]
 [3.31232751 3.07019612 3.0106914  ... 2.98698776 2.98781693 2.98766534]
 ...
 [3.32937152 3.0802138  3.02631181 ... 3.0059636  3.00547542 3.00687   ]
 [3.31650702 3.07073947 3.01456434 ... 2.99283445 2.99290316 2.99364272]
 [3.41977993 3.16163694 3.10854003 ... 3.08897445 3.08796557 3.089992  ]]


In [35]:
nR.shape

(610, 9724)

In [36]:
movies = pd.read_csv('movies.csv')

In [37]:
movies

movieId                                      title  \
0           1                           Toy Story (1995)   
1           2                             Jumanji (1995)   
2           3                    Grumpier Old Men (1995)   
3           4                   Waiting to Exhale (1995)   
4           5         Father of the Bride Part II (1995)   
...       ...                                        ...   
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                                           genres  
0     Adventure|Animation|Children|Comedy|Fantasy  
1                      Adventure|Children|Fantasy  
2                                  Comedy|Romance  
3                            Comedy|Drama|Romance  
4                                          Comedy  
...                                           ...  
9737              Action|Animation|Comedy|Fantasy  
9738                     Animation|Comedy|Fantasy  
9739                                        Drama  
9740                             Action|Animation  
9741                                       Comedy  

[9742 rows x 3 columns]

In [38]:
movies=movies[['movieId', 'title']]

In [39]:
movies

movieId                                      title
0           1                           Toy Story (1995)
1           2                             Jumanji (1995)
2           3                    Grumpier Old Men (1995)
3           4                   Waiting to Exhale (1995)
4           5         Father of the Bride Part II (1995)
...       ...                                        ...
9737   193581  Black Butler: Book of the Atlantic (2017)
9738   193583               No Game No Life: Zero (2017)
9739   193585                               Flint (2017)
9740   193587        Bungo Stray Dogs: Dead Apple (2018)
9741   193609        Andrew Dice Clay: Dice Rules (1991)

[9742 rows x 2 columns]

In [40]:
randomuser=movies.sample(n = 20)

In [41]:
randomuser

movieId                                              title
2599     3475                         Place in the Sun, A (1951)
739       963                      Inspector General, The (1949)
7100    70533  Evangelion: 1.0 You Are (Not) Alone (Evangerio...
5642    27416                               Jalla! Jalla! (2000)
768      1010                               Love Bug, The (1969)
492       567                                        Kika (1993)
8162   102602                                      Mimino (1977)
1108     1441                                Benny & Joon (1993)
6408    50942                       Wake Up, Ron Burgundy (2004)
2947     3951                            Two Family House (2000)
6293    47997                                   Idiocracy (2006)
8572   116823       The Hunger Games: Mockingjay - Part 1 (2014)
9252   155812                                   Get a Job (2016)
1790     2389                                      Psycho (1998)
1461     1984          Halloween III: Season of the Witch (1982)
9539   172587                 Vacations in Prostokvashino (1980)
6280    47646                                    Idlewild (2006)
3153     4240                               Just Visiting (2001)
4272     6237                     Glenn Miller Story, The (1953)
1495     2020                          Dangerous Liaisons (1988)

In [42]:
#randomuser2 = randomuser.set_index('movieId')

In [43]:
randomuser

movieId                                              title
2599     3475                         Place in the Sun, A (1951)
739       963                      Inspector General, The (1949)
7100    70533  Evangelion: 1.0 You Are (Not) Alone (Evangerio...
5642    27416                               Jalla! Jalla! (2000)
768      1010                               Love Bug, The (1969)
492       567                                        Kika (1993)
8162   102602                                      Mimino (1977)
1108     1441                                Benny & Joon (1993)
6408    50942                       Wake Up, Ron Burgundy (2004)
2947     3951                            Two Family House (2000)
6293    47997                                   Idiocracy (2006)
8572   116823       The Hunger Games: Mockingjay - Part 1 (2014)
9252   155812                                   Get a Job (2016)
1790     2389                                      Psycho (1998)
1461     1984          Halloween III: Season of the Witch (1982)
9539   172587                 Vacations in Prostokvashino (1980)
6280    47646                                    Idlewild (2006)
3153     4240                               Just Visiting (2001)
4272     6237                     Glenn Miller Story, The (1953)
1495     2020                          Dangerous Liaisons (1988)

In [44]:
randomuser['rating'] = np.random.randint(0,5, size=len(randomuser)).astype(float)

In [45]:
randomuser2 = randomuser['rating']
randomuser2

2599    3.0
739     4.0
7100    2.0
5642    3.0
768     3.0
492     2.0
8162    0.0
1108    1.0
6408    3.0
2947    2.0
6293    2.0
8572    4.0
9252    4.0
1790    3.0
1461    2.0
9539    3.0
6280    4.0
3153    3.0
4272    0.0
1495    0.0
Name: rating, dtype: float64

In [46]:
moviesandratings = pd.concat([movies, randomuser2], axis=1, sort=True)

In [47]:
moviesandratings

movieId                                      title  rating
0           1                           Toy Story (1995)     NaN
1           2                             Jumanji (1995)     NaN
2           3                    Grumpier Old Men (1995)     NaN
3           4                   Waiting to Exhale (1995)     NaN
4           5         Father of the Bride Part II (1995)     NaN
...       ...                                        ...     ...
9737   193581  Black Butler: Book of the Atlantic (2017)     NaN
9738   193583               No Game No Life: Zero (2017)     NaN
9739   193585                               Flint (2017)     NaN
9740   193587        Bungo Stray Dogs: Dead Apple (2018)     NaN
9741   193609        Andrew Dice Clay: Dice Rules (1991)     NaN

[9742 rows x 3 columns]

In [48]:
moviesandratings = pd.concat([randomuser2, movies], axis=1, join='outer')

In [49]:
moviesandratings

rating  movieId                                      title
0        NaN        1                           Toy Story (1995)
1        NaN        2                             Jumanji (1995)
2        NaN        3                    Grumpier Old Men (1995)
3        NaN        4                   Waiting to Exhale (1995)
4        NaN        5         Father of the Bride Part II (1995)
...      ...      ...                                        ...
9737     NaN   193581  Black Butler: Book of the Atlantic (2017)
9738     NaN   193583               No Game No Life: Zero (2017)
9739     NaN   193585                               Flint (2017)
9740     NaN   193587        Bungo Stray Dogs: Dead Apple (2018)
9741     NaN   193609        Andrew Dice Clay: Dice Rules (1991)

[9742 rows x 3 columns]

In [50]:
result = pd.concat([randomuser2, movies], axis=1, ignore_index=False)

In [51]:
result

rating  movieId                                      title
0        NaN        1                           Toy Story (1995)
1        NaN        2                             Jumanji (1995)
2        NaN        3                    Grumpier Old Men (1995)
3        NaN        4                   Waiting to Exhale (1995)
4        NaN        5         Father of the Bride Part II (1995)
...      ...      ...                                        ...
9737     NaN   193581  Black Butler: Book of the Atlantic (2017)
9738     NaN   193583               No Game No Life: Zero (2017)
9739     NaN   193585                               Flint (2017)
9740     NaN   193587        Bungo Stray Dogs: Dead Apple (2018)
9741     NaN   193609        Andrew Dice Clay: Dice Rules (1991)

[9742 rows x 3 columns]

In [52]:
result=result.fillna(3.0000)

In [53]:
result

rating  movieId                                      title
0        3.0        1                           Toy Story (1995)
1        3.0        2                             Jumanji (1995)
2        3.0        3                    Grumpier Old Men (1995)
3        3.0        4                   Waiting to Exhale (1995)
4        3.0        5         Father of the Bride Part II (1995)
...      ...      ...                                        ...
9737     3.0   193581  Black Butler: Book of the Atlantic (2017)
9738     3.0   193583               No Game No Life: Zero (2017)
9739     3.0   193585                               Flint (2017)
9740     3.0   193587        Bungo Stray Dogs: Dead Apple (2018)
9741     3.0   193609        Andrew Dice Clay: Dice Rules (1991)

[9742 rows x 3 columns]

In [54]:
ratingrandomuser=np.array(result.rating)

In [55]:
ratingrandomuser=ratingrandomuser.reshape(1,-1).tolist()

In [56]:
ratingrandomuser

[[3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,

In [57]:
list2 = [3]

In [58]:
list2 = list2*9724

In [59]:
len(list2)

9724

In [60]:
import random

In [61]:
for i in range (20):
    list2[random.randint(0,len(list2)-1)]=random.randint(0,5)
    i=i+1

In [62]:
list2

[3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,


In [63]:
list3=[[list2]]

In [64]:
list3=list3[0]

In [65]:
list3

[[3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,


In [66]:
array3=np.array(list2)

In [67]:
array3

array([3, 3, 3, ..., 3, 3, 3])

In [68]:
array3=array3.reshape(1,-1)

In [69]:
print(model.transform(array3))

[[1.25635573 1.15737139]]
